name: CI Testing

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Lint frontend
        run: npm run -w packages/travel-project-frontend lint

      - name: Build frontend
        run: npm run -w packages/travel-project-frontend build

      - name: Lint backend
        run: npm run -w packages/travel-project-backend lint

      - name: Build backend
        run:  npm run -w packages/travel-project-backend build