name: CI Testing

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v16
        with:
          node-version: 20
      - run: npm ci
      - run: npm run -w travel-project-backend lint
      - run: npm run -w travel-project-frontend lint
      - run: npm run -w travel-project-frontend build